site_name: Forge
site_url: https://www.forge.dev/
theme:
  name: material
  logo: assets/images/logo.png
  custom_dir: docs/overrides
  features:
      - content.code.copy
extra_css:
  - stylesheets/forge.css
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Overview: overview.md
  - System Design: system-design.md
  - ForgeRenderer: forge-renderer.md
  - ForgeViewpoint: forge-viewpoint.md
  - SplatMesh: splat-mesh.md
  - PackedSplats: packed-splats.md
  - Loading Gsplats: loading-splats.md
  - Procedural Splats: procedural-splats.md
  - Splat RGBA-XYZ SDF editing: splat-editing.md
  - Controls: controls.md
  - Performance tuning: performance.md
  - Community Resources: community-resources.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
